apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluentd-azure.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "fluentd-azure.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "fluentd-azure.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fluentd-azure.name" . }}
    spec:
      serviceAccount: {{ include "fluentd-azure.fullname" . }}
      serviceAccountName: {{ include "fluentd-azure.fullname" . }}
      tolerations: 
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - name: fluentd-nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: FLUENT_AZURE_STORAGE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: {{ include "fluentd-azure.fullname" . }}-secret
                key: storage-account
          - name: FLUENT_AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "fluentd-azure.fullname" . }}-secret
                key: access-key
        resources: 
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: {{ include "fluentd-azure.fullname" . }}
      - name: fluent-buffer
        hostPath:
          path: {{ .Values.fluentd.bufferPath }}
          type: DirectoryOrCreate
