apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd-azure.fullname" . }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluentd-azure.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluentd-azure.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluentd-azure.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fluentd-azure.fullname" . }}
  namespace: {{ .Values.namespace }}