apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluentd-azure.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  storage-account: {{ required "Azure storage container name is required" .Values.azure.storageAccount }}
  access-key: {{ required "Azure storage access key is required" .Values.azure.accessKey }}